[package]
name = "crml"
version = "0.1.3"
edition = "2024"
description = "Crab Markup Language CLI"
authors = ["trisuaso"]
license = "MIT"
repository = "https://github.com/trisuaso/crml"

[dependencies]
# crml-core = { path = "../crml-core" }
crml-core = "0.1.3"
pathbufd = "0.1.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
