[workspace]
resolver = "2"
members = ["crates/crml", "crates/crml-core", "crates/crml-derive"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
# panic = "abort"
panic = "unwind"
strip = true
